/* Generated by re2c 0.13.7.5 on Mon Mar 30 22:16:27 2015 */

#include "stdafx.h"

typedef unsigned char uchar;
typedef unsigned int uint;

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr

#define	RET(i)	{s->cur = cursor; return i;}
#define	RETT(i, typeid)	{s->cur = cursor; s->type = typeid; return i;}

class CMYMaterial
{
public:
  CMYMaterial() : shader(SHADER_Phong), uid(0), vcol(false), dbls(false), dif(0.8), amb(0.6), emi(0.0), spc(0.0), power(5.0), reflect(0.0), refract(1.0), proj_type(PROJTYPE_UV)
  {
    for(int i=0;i<4;i++)col[i]=1.0;
    for(int i=0;i<3;i++)
    {
      proj_scale[i]=1.0;
      proj_pos[i] = proj_angle[i] = amb_col[i] = emi_col[i] = spc_col[i] = 0;
    }
  }
public:
  CString name;
  enum SHADER {SHADER_Classic = 0, SHADER_Constant, SHADER_Lambert, SHADER_Phong, SHADER_Blinn } shader;
  uint uid;
  bool vcol;
  bool dbls; //double face
  double col[4];
  double dif;
  double amb;
  double amb_col[3];
  double emi;
  double emi_col[3];
  double spc;
  double spc_col[3];
  double power;
  double reflect;
  double refract;
  CString tex;
  CString aplane;
  CString bump;
  enum PROJTYPE {PROJTYPE_UV=0, PROJTYPE_PLANE, PROJTYPE_CYLINDER, PROJTYPE_SPHERE} proj_type;
  double proj_pos[3];
  double proj_scale[3];
  double proj_angle[3];
};

class CMYVertex
{
public:
  CMYVertex(double _x, double _y, double _z)
  {
    x = _x;
    y = _y;
    z = _z;
  }
	double x, y, z;
};

class CMYFace
{
public:
  CMYFace() : M(0), V(NULL), UV(NULL), COL(NULL)
  {
  }
  ~CMYFace()
  {
    if(V)
    {
      delete V;
      V = NULL;
    }
    if(UV)
    {
      delete UV;
      UV = NULL;
    }
    if(COL)
    {
      delete COL;
      COL = NULL;
    }
  }
  CAtlArray<uint> *V;
  int M;
  CAtlArray<double> *UV;
  CAtlArray<COLORREF> *COL;
//  CAtlArray<double> *CRS;
};

class CMYObject
{
public:
  CMYObject() : vertex(NULL), face(NULL), pFbxNode(NULL)
  {
  }
  ~CMYObject()
  {
    if(vertex)
    {
      int m=vertex->GetCount();;
      for(int i=0;i<m;i++)delete (*vertex)[i];
      vertex = NULL;
    }
    if(face)
    {
      int m=face->GetCount();;
      for(int i=0;i<m;i++)delete (*face)[i];
      face = NULL;
    }
  }
  FbxNode *pFbxNode;
  CString name;
  int uid;
  int depth;
  bool folding;
  double scale[3];
  double rotation[3];
  double translation[3];
  //enum {PATCH_PLANE=0, PATCH_SPLINE1, PATCH_SPLINE2, PATCH_CATMULLCLARK, PATCH_OPENSUBDIV} patch;
  //bool patchtri;
  //int segment;
  //bool visible;
  //bool locking;
  enum SHADING {SHADING_FLAT=0, SHADING_GLOW} shading;
  //double facet;
  double color[3];
  bool color_type;
  //enum MIRROR {MIRROR_NONE=0, MIRROR_SPLIT, MIRROR_CONNECT} mirror;
  //enum MIRRORAXIS {MIRRORAXIS_X=0, MIRRORAXIS_Y, MIRRORAXIS_Z} mirroraxis;
  //double mirror_dis;
  //bool lathe;
  //enum LATHEAXIS {LATHEAXIS_X=0, LATHEAXIS_Y, LATHEAXIS_Z} lathe_axis;
  //int lathe_seg;
  CAtlArray<CMYVertex*> *vertex;
  CAtlArray<CMYFace*> *face;
};

class CMYBone
{
  public:
    CMYBone() : parent(NULL), id(0), P(0), rtX(0), rtY(0), rtZ(0), tpX(0), tpY(0), tpZ(0), rotB(0), rotH(0), rotP(0), mvX(0), mvY(0), mvZ(0), scX(0), scY(0), scZ(0), fbxNode(NULL)
    {
    }
    ~CMYBone()
    {
    }
    CMYBone *parent;
    CAtlArray<CMYBone*> childs;
    int id;
    CString name;
    FbxNode *fbxNode;
    
    int P;
    CAtlArray<int> C;
    CAtlArray<int> oi;
    CAtlArray<int> vi;
    CAtlArray<double> w;
    
    double rtX, rtY, rtZ;
    double tpX, tpY, tpZ;
    double rotB, rotH, rotP;
    double mvX, mvY, mvZ;
    double scX, scY, scZ;
};

class CMYMQO
{
public:
  int m_currentMaterialIndex;
  CAtlArray<CMYMaterial*> m_materials;
  CAtlArray<CMYObject*> m_objects;
  CAtlArray<CMYBone> m_bones;
//  CAtlArray<int> m_boneObjIndex;
  
  CMYMQO() : m_currentMaterialIndex(-1)
  {
  }
  
  ~CMYMQO()
  {
    int s = m_materials.GetCount();
    for(int i=0;i<s;i++)
    {
      delete m_materials[i];
    }
    m_materials.RemoveAll();
  }
  
  CMYMaterial* GetCurrentMaterial()
  {
    if(m_currentMaterialIndex==-1)
    {
      CMYMaterial *pMat = new CMYMaterial();
      if(pMat==NULL)return NULL;
      m_materials.Add(pMat);
      m_currentMaterialIndex = m_materials.GetCount()-1;
      return pMat;
    } else {
      return m_materials[m_currentMaterialIndex];
    }
  }
  CMYMaterial* ClearCurrentMaterial()
  {
    m_currentMaterialIndex = -1;
  }
  void AddMaterial(CMYMaterial *pMat)
  {
    m_materials.Add(pMat);
  }
  
  CMYBone *AddBone(const char *name)
  {
    int idx = m_bones.Add();
    m_bones[idx].name = name;
    return &(m_bones[idx]);
  }
  CMYBone *FindBone(int id)
  {
    int m = m_bones.GetCount();
    for(int i=0;i<m;i++)
    {
      if(m_bones[i].id==id)return &(m_bones[i]);
    }
    return NULL;
  }
};

typedef struct PassData
{
  union {
    __int64 i;
    double dbl;
    CString *str;
  };
} PassData;

typedef struct Scanner
{
    int			fd;
    uchar		*bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
    uint		line;
    PassData val;
} Scanner;

/*enum {
 TAG_MetasequoiaDocument, TAG_FormatTextVer11, TAG_Thumbnail, TAG_IncludeXml, TAG_Scene, TAG_pos, TAG_lookat, TAG_head, TAG_pich, TAG_bank, TAG_ortho, TAG_zoom2, TAG_amb, TAG_frontclip, TAG_backclip, TAG_dirlights, TAG_light, TAG_dir, TAG_color, 
 TAG_Material, TAG_shader, TAG_vcol, TAG_dbls, TAG_col, TAG_uid, TAG_dif, TAG_amb, TAG_emi, TAG_spc, TAG_power, TAG_reflect, TAG_refract, TAG_tex, TAG_aplane, TAG_bump, TAG_proj_type, TAG_proj_pos, TAG_proj_scale, TAG_proj_angle, 
 TAG_Object, TAG_depth, TAG_folding, TAG_scale, TAG_rotation, TAG_translation, TAG_patch, TAG_patchtri, TAG_segment, TAG_visible, TAG_locking, TAG_shading, TAG_facet, TAG_color, TAG_color_type, TAG_mirror, TAG_mirror_axis, TAG_mirror_dis, TAG_lathe, TAG_lathe_axis, TAG_lathe_seg, TAG_vertex, TAG_BVertex, TAG_vertexattr, TAG_weit, TAG_face, TAG_V, TAG_M, TAG_UID, TAG_UV, TAG_COL, TAG_CRS, TAG_Blob, 
 TAG_Eof};*/


#include "MQOParser.h"
#include "MQOParser.c"


CString ReadStr(uchar *token, uint len)
{
  CStringA tmpA;
  tmpA.SetString((const char *)token, len);
  CStringW tmpB = CA2W(tmpA, CP_UTF8);
  tmpB.Replace(L"%", L"%%");
  CString retStr;
  retStr.Format(tmpB);
  return retStr;
}

BOOL fill(int n) { return FALSE; }

int scan(Scanner *s){
	uchar *cursor = s->cur;
std:
	s->tok = cursor;



{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 20) if(!fill(20)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy32;
	case '\n':	goto yy49;
	case '\v':
	case '\f':	goto yy48;
	case '\r':	goto yy51;
	case 0x1A:	goto yy46;
	case '"':	goto yy37;
	case '(':	goto yy38;
	case ')':	goto yy40;
	case '+':
	case '-':	goto yy31;
	case '.':	goto yy36;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy34;
	case 'B':	goto yy9;
	case 'C':	goto yy29;
	case 'E':	goto yy30;
	case 'F':	goto yy4;
	case 'I':	goto yy7;
	case 'M':	goto yy2;
	case 'O':	goto yy21;
	case 'S':	goto yy8;
	case 'T':	goto yy6;
	case 'U':	goto yy28;
	case 'V':	goto yy26;
	case 'a':	goto yy15;
	case 'b':	goto yy20;
	case 'c':	goto yy10;
	case 'd':	goto yy13;
	case 'e':	goto yy16;
	case 'f':	goto yy22;
	case 'l':	goto yy23;
	case 'm':	goto yy24;
	case 'p':	goto yy17;
	case 'r':	goto yy18;
	case 's':	goto yy11;
	case 't':	goto yy19;
	case 'u':	goto yy14;
	case 'v':	goto yy12;
	case 'w':	goto yy25;
	case '{':	goto yy42;
	case '}':	goto yy44;
	default:	goto yy52;
	}
yy2:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy395;
	case 'e':	goto yy396;
	default:	goto yy3;
	}
yy3:
	{ RET(TAG_M); }
yy4:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy376;
	default:	goto yy5;
	}
yy5:
	{
    ATLTRACE("unexpected character: %c\n", *s->tok);
    goto std;
  }
yy6:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'h':	goto yy367;
	default:	goto yy5;
	}
yy7:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'n':	goto yy357;
	default:	goto yy5;
	}
yy8:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'c':	goto yy352;
	default:	goto yy5;
	}
yy9:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'V':	goto yy333;
	case 'a':	goto yy334;
	case 'l':	goto yy332;
	default:	goto yy5;
	}
yy10:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy320;
	default:	goto yy5;
	}
yy11:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'c':	goto yy292;
	case 'e':	goto yy291;
	case 'h':	goto yy290;
	case 'p':	goto yy293;
	default:	goto yy5;
	}
yy12:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'c':	goto yy270;
	case 'e':	goto yy268;
	case 'i':	goto yy269;
	default:	goto yy5;
	}
yy13:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'b':	goto yy258;
	case 'e':	goto yy256;
	case 'i':	goto yy257;
	default:	goto yy5;
	}
yy14:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy253;
	default:	goto yy5;
	}
yy15:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'm':	goto yy240;
	case 'p':	goto yy239;
	default:	goto yy5;
	}
yy16:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'm':	goto yy231;
	default:	goto yy5;
	}
yy17:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy192;
	case 'o':	goto yy194;
	case 'r':	goto yy193;
	default:	goto yy5;
	}
yy18:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy173;
	case 'o':	goto yy172;
	default:	goto yy5;
	}
yy19:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy159;
	case 'r':	goto yy158;
	default:	goto yy5;
	}
yy20:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'u':	goto yy154;
	default:	goto yy5;
	}
yy21:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'b':	goto yy148;
	default:	goto yy5;
	}
yy22:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy135;
	case 'o':	goto yy136;
	default:	goto yy5;
	}
yy23:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy113;
	case 'o':	goto yy114;
	default:	goto yy5;
	}
yy24:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy97;
	default:	goto yy5;
	}
yy25:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy93;
	default:	goto yy5;
	}
yy26:
	++YYCURSOR;
	{ RET(TAG_V); }
yy28:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'I':	goto yy90;
	case 'V':	goto yy88;
	default:	goto yy5;
	}
yy29:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'O':	goto yy83;
	case 'R':	goto yy82;
	default:	goto yy5;
	}
yy30:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy79;
	default:	goto yy5;
	}
yy31:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case ' ':	goto yy77;
	case '.':	goto yy76;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy5;
	}
yy32:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy75;
yy33:
	{ if(cursor == s->eof)RET(0); goto std; }
yy34:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':	goto yy72;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy35;
	}
yy35:
	{ uchar *start = s->tok;
				bool bMinus = false;
				if(*start == '-')bMinus = true;
				while(*start<'0' || *start>'9')start++;
				CStringA tmp;
				tmp.SetString((const char *)(start), cursor - start);
				s->val.i = bMinus ? -_atoi64(tmp) : _atoi64(tmp);
				RET(INTVAL); }
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy67;
	default:	goto yy5;
	}
yy37:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy5;
	default:	goto yy57;
	}
yy38:
	++YYCURSOR;
	{ RET(BR3); }
yy40:
	++YYCURSOR;
	{ RET(BR4); }
yy42:
	++YYCURSOR;
	{ RET(BR1); }
yy44:
	++YYCURSOR;
	{ RET(BR2); }
yy46:
	++YYCURSOR;
	{ RET(0);/*EOF*/ }
yy48:
	yych = *++YYCURSOR;
	goto yy55;
yy49:
	++YYCURSOR;
yy50:
	{
    if(cursor == s->eof)RET(0);
    s->pos = cursor; s->line++;
    goto std;
  }
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy53;
	default:	goto yy50;
	}
yy52:
	yych = *++YYCURSOR;
	goto yy5;
yy53:
	yych = *++YYCURSOR;
	goto yy50;
yy54:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy55:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy54;
	default:	goto yy33;
	}
yy56:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy57:
	switch (yych) {
	case '\n':	goto yy58;
	case '"':	goto yy60;
	case '\\':	goto yy59;
	default:	goto yy56;
	}
yy58:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy3;
	case 1: 	goto yy5;
	case 2: 	goto yy33;
	case 3: 	goto yy102;
	case 4: 	goto yy124;
	case 5: 	goto yy226;
	case 6: 	goto yy233;
	case 7: 	goto yy242;
	case 8: 	goto yy284;
	case 9: 	goto yy295;
	case 10: 	goto yy322;
	case 11: 	goto yy325;
	default:	goto yy422;
	}
yy59:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy56;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy63;
	case 'x':	goto yy62;
	default:	goto yy58;
	}
yy60:
	++YYCURSOR;
	{ s->val.str = new CString(); *(s->val.str) = ReadStr(s->tok + 1, cursor - s->tok -2); RET(STRVAL); }
yy62:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy65;
	default:	goto yy58;
	}
yy63:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy58;
	case '"':	goto yy60;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy63;
	case '\\':	goto yy59;
	default:	goto yy56;
	}
yy65:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy58;
	case '"':	goto yy60;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy65;
	case '\\':	goto yy59;
	default:	goto yy56;
	}
yy67:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy67;
	default:	goto yy69;
	}
yy69:
	{ uchar *start = s->tok;
				bool bMinus = false;
				if(*start == '-')bMinus = true;
				while(!((*start>='0' && *start<='9') || *start=='.'))start++;
				CStringA tmp;
				tmp.SetString((const char *)(start), cursor - start);
				s->val.dbl = bMinus ? -atof(tmp) : atof(tmp);
				RET(DBLVAL); }
yy70:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy72;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy35;
	}
yy72:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy72;
	default:	goto yy69;
	}
yy74:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) if(!fill(2)) { return 0; }
	yych = *YYCURSOR;
yy75:
	switch (yych) {
	case '\t':
	case ' ':	goto yy74;
	case '\v':
	case '\f':	goto yy54;
	case '.':	goto yy76;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy33;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy67;
	default:	goto yy58;
	}
yy77:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) if(!fill(2)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy77;
	case '.':	goto yy76;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy58;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy80;
	default:	goto yy58;
	}
yy80:
	++YYCURSOR;
	{ RET(TAG_Eof); }
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy86;
	default:	goto yy58;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy84;
	default:	goto yy58;
	}
yy84:
	++YYCURSOR;
	{ RET(TAG_COL); }
yy86:
	++YYCURSOR;
	{ RET(TAG_CRS); }
yy88:
	++YYCURSOR;
	{ RET(TAG_UV); }
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':	goto yy91;
	default:	goto yy58;
	}
yy91:
	++YYCURSOR;
	{ RET(TAG_UID); }
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy94;
	default:	goto yy58;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy95;
	default:	goto yy58;
	}
yy95:
	++YYCURSOR;
	{ RET(TAG_weit); }
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy98;
	default:	goto yy58;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy99;
	default:	goto yy58;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy100;
	default:	goto yy58;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy101;
	default:	goto yy58;
	}
yy101:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy103;
	default:	goto yy102;
	}
yy102:
	{ RET(TAG_mirror); }
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy105;
	case 'd':	goto yy104;
	default:	goto yy58;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy110;
	default:	goto yy58;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy106;
	default:	goto yy58;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy107;
	default:	goto yy58;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy108;
	default:	goto yy58;
	}
yy108:
	++YYCURSOR;
	{ RET(TAG_mirror_axis); }
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy111;
	default:	goto yy58;
	}
yy111:
	++YYCURSOR;
	{ RET(TAG_mirror_dis); }
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy121;
	default:	goto yy58;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy115;
	default:	goto yy58;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy116;
	default:	goto yy58;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy117;
	default:	goto yy58;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy118;
	default:	goto yy58;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy119;
	default:	goto yy58;
	}
yy119:
	++YYCURSOR;
	{ RET(TAG_locking); }
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy122;
	default:	goto yy58;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy123;
	default:	goto yy58;
	}
yy123:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy125;
	default:	goto yy124;
	}
yy124:
	{ RET(TAG_lathe); }
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy126;
	case 's':	goto yy127;
	default:	goto yy58;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy131;
	default:	goto yy58;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy128;
	default:	goto yy58;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy129;
	default:	goto yy58;
	}
yy129:
	++YYCURSOR;
	{ RET(TAG_lathe_seg); }
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy132;
	default:	goto yy58;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy133;
	default:	goto yy58;
	}
yy133:
	++YYCURSOR;
	{ RET(TAG_lathe_axis); }
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy143;
	default:	goto yy58;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy137;
	default:	goto yy58;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy138;
	default:	goto yy58;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy139;
	default:	goto yy58;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy140;
	default:	goto yy58;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy141;
	default:	goto yy58;
	}
yy141:
	++YYCURSOR;
	{ RET(TAG_folding); }
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy144;
	default:	goto yy58;
	}
yy144:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 't':	goto yy146;
	default:	goto yy145;
	}
yy145:
	{ RET(TAG_face); }
yy146:
	++YYCURSOR;
	{ RET(TAG_facet); }
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'j':	goto yy149;
	default:	goto yy58;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy150;
	default:	goto yy58;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy151;
	default:	goto yy58;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy152;
	default:	goto yy58;
	}
yy152:
	++YYCURSOR;
	{ RET(TAG_Object); }
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy155;
	default:	goto yy58;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy156;
	default:	goto yy58;
	}
yy156:
	++YYCURSOR;
	{ RET(TAG_bump); }
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy162;
	default:	goto yy58;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy160;
	default:	goto yy58;
	}
yy160:
	++YYCURSOR;
	{ RET(TAG_tex); }
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy163;
	default:	goto yy58;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy164;
	default:	goto yy58;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy165;
	default:	goto yy58;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy166;
	default:	goto yy58;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy167;
	default:	goto yy58;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy168;
	default:	goto yy58;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy169;
	default:	goto yy58;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy170;
	default:	goto yy58;
	}
yy170:
	++YYCURSOR;
	{ RET(TAG_translation); }
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy185;
	default:	goto yy58;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy174;
	default:	goto yy58;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy176;
	case 'r':	goto yy175;
	default:	goto yy58;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy181;
	default:	goto yy58;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy177;
	default:	goto yy58;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy178;
	default:	goto yy58;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy179;
	default:	goto yy58;
	}
yy179:
	++YYCURSOR;
	{ RET(TAG_reflect); }
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy182;
	default:	goto yy58;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy183;
	default:	goto yy58;
	}
yy183:
	++YYCURSOR;
	{ RET(TAG_refract); }
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy186;
	default:	goto yy58;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy187;
	default:	goto yy58;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy188;
	default:	goto yy58;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy189;
	default:	goto yy58;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy190;
	default:	goto yy58;
	}
yy190:
	++YYCURSOR;
	{ RET(TAG_rotation); }
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy223;
	default:	goto yy58;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy199;
	default:	goto yy58;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy195;
	default:	goto yy58;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy196;
	default:	goto yy58;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy197;
	default:	goto yy58;
	}
yy197:
	++YYCURSOR;
	{ RET(TAG_power); }
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'j':	goto yy200;
	default:	goto yy58;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy201;
	default:	goto yy58;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy202;
	case 'p':	goto yy204;
	case 's':	goto yy203;
	case 't':	goto yy205;
	default:	goto yy58;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy218;
	default:	goto yy58;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy213;
	default:	goto yy58;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy210;
	default:	goto yy58;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy206;
	default:	goto yy58;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy207;
	default:	goto yy58;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy208;
	default:	goto yy58;
	}
yy208:
	++YYCURSOR;
	{ RET(TAG_proj_type); }
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy211;
	default:	goto yy58;
	}
yy211:
	++YYCURSOR;
	{ RET(TAG_proj_pos); }
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy214;
	default:	goto yy58;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy215;
	default:	goto yy58;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy216;
	default:	goto yy58;
	}
yy216:
	++YYCURSOR;
	{ RET(TAG_proj_scale); }
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy219;
	default:	goto yy58;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy220;
	default:	goto yy58;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy221;
	default:	goto yy58;
	}
yy221:
	++YYCURSOR;
	{ RET(TAG_proj_angle); }
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy224;
	default:	goto yy58;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy225;
	default:	goto yy58;
	}
yy225:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 't':	goto yy227;
	default:	goto yy226;
	}
yy226:
	{ RET(TAG_patch); }
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy228;
	default:	goto yy58;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy229;
	default:	goto yy58;
	}
yy229:
	++YYCURSOR;
	{ RET(TAG_patchtri); }
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy232;
	default:	goto yy58;
	}
yy232:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy234;
	default:	goto yy233;
	}
yy233:
	{ RET(TAG_emi); }
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy235;
	default:	goto yy58;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy236;
	default:	goto yy58;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy237;
	default:	goto yy58;
	}
yy237:
	++YYCURSOR;
	{ RET(TAG_emi_col); }
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy248;
	default:	goto yy58;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy241;
	default:	goto yy58;
	}
yy241:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy243;
	default:	goto yy242;
	}
yy242:
	{ RET(TAG_amb); }
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy244;
	default:	goto yy58;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy245;
	default:	goto yy58;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy246;
	default:	goto yy58;
	}
yy246:
	++YYCURSOR;
	{ RET(TAG_amb_col); }
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy249;
	default:	goto yy58;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy250;
	default:	goto yy58;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy251;
	default:	goto yy58;
	}
yy251:
	++YYCURSOR;
	{ RET(TAG_aplane); }
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy254;
	default:	goto yy58;
	}
yy254:
	++YYCURSOR;
	{ RET(TAG_uid); }
yy256:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy264;
	default:	goto yy58;
	}
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy262;
	default:	goto yy58;
	}
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy259;
	default:	goto yy58;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy260;
	default:	goto yy58;
	}
yy260:
	++YYCURSOR;
	{ RET(TAG_dbls); }
yy262:
	++YYCURSOR;
	{ RET(TAG_dif); }
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy265;
	default:	goto yy58;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy266;
	default:	goto yy58;
	}
yy266:
	++YYCURSOR;
	{ RET(TAG_depth); }
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy280;
	default:	goto yy58;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy274;
	default:	goto yy58;
	}
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy271;
	default:	goto yy58;
	}
yy271:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy272;
	default:	goto yy58;
	}
yy272:
	++YYCURSOR;
	{ RET(TAG_vcol); }
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy275;
	default:	goto yy58;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy276;
	default:	goto yy58;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy277;
	default:	goto yy58;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy278;
	default:	goto yy58;
	}
yy278:
	++YYCURSOR;
	{ RET(TAG_visible); }
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy281;
	default:	goto yy58;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy282;
	default:	goto yy58;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy283;
	default:	goto yy58;
	}
yy283:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy285;
	default:	goto yy284;
	}
yy284:
	{ RET(TAG_vertex); }
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy286;
	default:	goto yy58;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy287;
	default:	goto yy58;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy288;
	default:	goto yy58;
	}
yy288:
	++YYCURSOR;
	{ RET(TAG_vertexattr); }
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy311;
	default:	goto yy58;
	}
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy305;
	default:	goto yy58;
	}
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy301;
	default:	goto yy58;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy294;
	default:	goto yy58;
	}
yy294:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy296;
	default:	goto yy295;
	}
yy295:
	{ RET(TAG_spc); }
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy297;
	default:	goto yy58;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy298;
	default:	goto yy58;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy299;
	default:	goto yy58;
	}
yy299:
	++YYCURSOR;
	{ RET(TAG_spc_col); }
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy302;
	default:	goto yy58;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy303;
	default:	goto yy58;
	}
yy303:
	++YYCURSOR;
	{ RET(TAG_scale); }
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy306;
	default:	goto yy58;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy307;
	default:	goto yy58;
	}
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy308;
	default:	goto yy58;
	}
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy309;
	default:	goto yy58;
	}
yy309:
	++YYCURSOR;
	{ RET(TAG_segment); }
yy311:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy312;
	default:	goto yy58;
	}
yy312:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy313;
	case 'i':	goto yy314;
	default:	goto yy58;
	}
yy313:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy318;
	default:	goto yy58;
	}
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy315;
	default:	goto yy58;
	}
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy316;
	default:	goto yy58;
	}
yy316:
	++YYCURSOR;
	{ RET(TAG_shading); }
yy318:
	++YYCURSOR;
	{ RET(TAG_shader); }
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy321;
	default:	goto yy58;
	}
yy321:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy323;
	default:	goto yy322;
	}
yy322:
	{ RET(TAG_col); }
yy323:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy324;
	default:	goto yy58;
	}
yy324:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy326;
	default:	goto yy325;
	}
yy325:
	{ RET(TAG_color); }
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy327;
	default:	goto yy58;
	}
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy328;
	default:	goto yy58;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy329;
	default:	goto yy58;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy330;
	default:	goto yy58;
	}
yy330:
	++YYCURSOR;
	{ RET(TAG_color_type); }
yy332:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy349;
	default:	goto yy58;
	}
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy343;
	default:	goto yy58;
	}
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy335;
	default:	goto yy58;
	}
yy335:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy336;
	default:	goto yy58;
	}
yy336:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'I':	goto yy337;
	default:	goto yy58;
	}
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy338;
	default:	goto yy58;
	}
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy339;
	default:	goto yy58;
	}
yy339:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy340;
	default:	goto yy58;
	}
yy340:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy341;
	default:	goto yy58;
	}
yy341:
	++YYCURSOR;
	{ goto brskip; }
yy343:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy344;
	default:	goto yy58;
	}
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy345;
	default:	goto yy58;
	}
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy346;
	default:	goto yy58;
	}
yy346:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy347;
	default:	goto yy58;
	}
yy347:
	++YYCURSOR;
	{ goto brskip; }
yy349:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy350;
	default:	goto yy58;
	}
yy350:
	++YYCURSOR;
	{ goto brskip; }
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy353;
	default:	goto yy58;
	}
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy354;
	default:	goto yy58;
	}
yy354:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy355;
	default:	goto yy58;
	}
yy355:
	++YYCURSOR;
	{ goto brskip; }
yy357:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy358;
	default:	goto yy58;
	}
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy359;
	default:	goto yy58;
	}
yy359:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy360;
	default:	goto yy58;
	}
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy361;
	default:	goto yy58;
	}
yy361:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy362;
	default:	goto yy58;
	}
yy362:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'X':	goto yy363;
	default:	goto yy58;
	}
yy363:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy364;
	default:	goto yy58;
	}
yy364:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy365;
	default:	goto yy58;
	}
yy365:
	++YYCURSOR;
	{ RET(TAG_IncludeXml); }
yy367:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy368;
	default:	goto yy58;
	}
yy368:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy369;
	default:	goto yy58;
	}
yy369:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy370;
	default:	goto yy58;
	}
yy370:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy371;
	default:	goto yy58;
	}
yy371:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy372;
	default:	goto yy58;
	}
yy372:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy373;
	default:	goto yy58;
	}
yy373:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy374;
	default:	goto yy58;
	}
yy374:
	++YYCURSOR;
	{ goto brskip; }
yy376:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy377;
	default:	goto yy58;
	}
yy377:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy378;
	default:	goto yy58;
	}
yy378:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy379;
	default:	goto yy58;
	}
yy379:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy380;
	default:	goto yy58;
	}
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy381;
	default:	goto yy58;
	}
yy381:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy382;
	default:	goto yy58;
	}
yy382:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy383;
	default:	goto yy58;
	}
yy383:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy384;
	default:	goto yy58;
	}
yy384:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy385;
	default:	goto yy58;
	}
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy386;
	default:	goto yy58;
	}
yy386:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy387;
	default:	goto yy58;
	}
yy387:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy388;
	default:	goto yy58;
	}
yy388:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy389;
	default:	goto yy58;
	}
yy389:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy390;
	default:	goto yy58;
	}
yy390:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':	goto yy391;
	default:	goto yy58;
	}
yy391:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy392;
	default:	goto yy58;
	}
yy392:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':	goto yy393;
	default:	goto yy58;
	}
yy393:
	++YYCURSOR;
	{ RET(TAG_FormatTextVer11); }
yy395:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy416;
	default:	goto yy58;
	}
yy396:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy397;
	default:	goto yy58;
	}
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy398;
	default:	goto yy58;
	}
yy398:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy399;
	default:	goto yy58;
	}
yy399:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy400;
	default:	goto yy58;
	}
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'q':	goto yy401;
	default:	goto yy58;
	}
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy402;
	default:	goto yy58;
	}
yy402:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy403;
	default:	goto yy58;
	}
yy403:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy404;
	default:	goto yy58;
	}
yy404:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy405;
	default:	goto yy58;
	}
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy406;
	default:	goto yy58;
	}
yy406:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':	goto yy407;
	default:	goto yy58;
	}
yy407:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy408;
	default:	goto yy58;
	}
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy409;
	default:	goto yy58;
	}
yy409:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy410;
	default:	goto yy58;
	}
yy410:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy411;
	default:	goto yy58;
	}
yy411:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy412;
	default:	goto yy58;
	}
yy412:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy413;
	default:	goto yy58;
	}
yy413:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy414;
	default:	goto yy58;
	}
yy414:
	++YYCURSOR;
	{ RET(TAG_MetasequoiaDocument); }
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy417;
	default:	goto yy58;
	}
yy417:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy418;
	default:	goto yy58;
	}
yy418:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy419;
	default:	goto yy58;
	}
yy419:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy420;
	default:	goto yy58;
	}
yy420:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy421;
	default:	goto yy58;
	}
yy421:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':	goto yy423;
	default:	goto yy422;
	}
yy422:
	{ RET(TAG_Material); }
yy423:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy424;
	default:	goto yy58;
	}
yy424:
	++YYCURSOR;
	{ goto brskip; }
}


brskip:
  {
    int cntBr = 0;
brskip2:

{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy432;
	case '{':	goto yy428;
	case '}':	goto yy430;
	default:	goto yy434;
	}
yy428:
	++YYCURSOR;
	{ if(cursor == s->eof)RET(0); cntBr++; goto brskip2; }
yy430:
	++YYCURSOR;
	{ if(cursor == s->eof || cursor+1 == s->eof)RET(0); cntBr--; if(cntBr<=0)goto std; }
yy432:
	++YYCURSOR;
	{ if(cursor == s->eof) RET(0); s->tok = s->pos = cursor; s->line++; goto brskip2; }
yy434:
	++YYCURSOR;
	{ if(cursor == s->eof)RET(0); goto brskip2; }
}

  }
}