#define TAG_MetasequoiaDocument          1
#define TAG_FormatTextVer11              2
#define TAG_Eof                          3
#define TAG_Material                     4
#define BR1                              5
#define BR2                              6
#define TAG_Object                       7
#define TAG_IncludeXml                   8
#define INTVAL                           9
#define DBLVAL                          10
#define STRVAL                          11
#define TAG_shader                      12
#define BR3                             13
#define BR4                             14
#define TAG_uid                         15
#define TAG_vcol                        16
#define TAG_dbls                        17
#define TAG_col                         18
#define TAG_dif                         19
#define TAG_amb                         20
#define TAG_emi                         21
#define TAG_spc                         22
#define TAG_amb_col                     23
#define TAG_emi_col                     24
#define TAG_spc_col                     25
#define TAG_power                       26
#define TAG_reflect                     27
#define TAG_refract                     28
#define TAG_tex                         29
#define TAG_aplane                      30
#define TAG_bump                        31
#define TAG_proj_type                   32
#define TAG_proj_pos                    33
#define TAG_proj_scale                  34
#define TAG_proj_angle                  35
#define TAG_depth                       36
#define TAG_folding                     37
#define TAG_scale                       38
#define TAG_rotation                    39
#define TAG_translation                 40
#define TAG_patch                       41
#define TAG_patchtri                    42
#define TAG_patchsmoothtri              43
#define TAG_patchlimitsurface           44
#define TAG_patchmeshinterp             45
#define TAG_patchuvinterp               46
#define TAG_segment                     47
#define TAG_visible                     48
#define TAG_locking                     49
#define TAG_shading                     50
#define TAG_facet                       51
#define TAG_normal_weight               52
#define TAG_color                       53
#define TAG_color_type                  54
#define TAG_mirror                      55
#define TAG_mirror_axis                 56
#define TAG_mirror_dis                  57
#define TAG_lathe                       58
#define TAG_lathe_axis                  59
#define TAG_lathe_seg                   60
#define TAG_vertex                      61
#define TAG_vertexattr                  62
#define TAG_face                        63
#define TAG_weit                        64
#define TAG_V                           65
#define TAG_M                           66
#define TAG_UID                         67
#define TAG_UV                          68
#define TAG_COL                         69
#define TAG_CRS                         70
#define TAG_N                           71
